#include<iostream>
using namespace std;
int main(){
    int i,t,n;
    cin>>t;
    while(t--){
        cin>>n;
        for(i = n; i > 1; i--){
            cout<<"2^"<<i<<" + ";
        }
        cout<<"2 + 1"<<endl;
    }
    return 0;
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           